import type { Metadata } from "next";

import { FileText, Scale, Zap, Globe, ArrowLeft, Shield } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Terms of Service",
    description: "Review the Mardis terms of service, acceptable use policy, and platform responsibilities.",
    alternates: {
        canonical: "/terms"
    }
};

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-[#0A0A0A] text-white font-sans selection:bg-primary/30">
            {/* Background elements */}
            <div className="fixed inset-0 overflow-hidden pointer-events-none">
                <div className="absolute top-[-10%] right-[-10%] w-[40%] h-[40%] bg-primary/10 blur-[120px] rounded-full" />
                <div className="absolute bottom-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/10 blur-[120px] rounded-full" />
            </div>

            <div className="relative max-w-4xl mx-auto px-6 py-20">
                <Link
                    href="/"
                    className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors mb-12 group"
                >
                    <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                    Back to Home
                </Link>

                <div className="space-y-4 mb-16">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-stone-300 text-xs font-bold uppercase tracking-widest">
                        <Scale className="w-3 h-3" /> Terms of Service
                    </div>
                    <h1 className="text-5xl font-black tracking-tight">Legal Terms</h1>
                    <p className="text-zinc-400 text-sm font-medium leading-relaxed max-w-2xl">
                        By accessing Mardis, you agree to be bound by these functional and ethical standards. Our platform is designed for professional growth and high-integrity outreach.
                    </p>
                </div>

                <div className="grid gap-8 mt-16">
                    <Section
                        icon={<Zap className="w-5 h-5 text-stone-300" />}
                        title="1. Acceptable Use Policy"
                    >
                        <p className="text-zinc-400">Mardis provides elite tools for lead discovery. By using our platform, you agree to:</p>
                        <ul className="list-disc list-inside space-y-3 mt-4 text-muted-foreground">
                            <li><span className="text-zinc-200">No Spam Engagement:</span> You will not use our AI to generate high-volume, low-quality spam or harassment.</li>
                            <li><span className="text-zinc-200">System Integrity:</span> You will not attempt to scrape Mardis data or bypass our security protocols.</li>
                            <li><span className="text-zinc-200">Handle Responsibility:</span> You are responsible for all actions taken through your connected social accounts.</li>
                        </ul>
                    </Section>

                    <Section
                        icon={<Globe className="w-5 h-5 text-stone-300" />}
                        title="2. AI Attribution & Accuracy"
                    >
                        <p className="text-zinc-400">Our personalized signals and DMs are generated by Large Language Models (LLMs). While highly effective:</p>
                        <ul className="list-disc list-inside space-y-3 mt-4 text-muted-foreground">
                            <li><span className="text-zinc-200">Review Requirement:</span> You are the final human-in-the-loop. You must review and approve all content before execution.</li>
                            <li><span className="text-zinc-200">Non-Reliance:</span> We do not guarantee the factual accuracy of AI-generated insights.</li>
                            <li><span className="text-zinc-200">Platform Compliance:</span> You must ensure your use of Mardis aligns with the Terms of Service of X (Twitter) and LinkedIn.</li>
                        </ul>
                    </Section>

                    <Section
                        icon={<FileText className="w-5 h-5 text-stone-300" />}
                        title="3. Subscriptions & Billing"
                    >
                        <p className="text-zinc-400">Access to the Mardis Alpha Deck is provided via subscription:</p>
                        <ul className="list-disc list-inside space-y-3 mt-4 text-muted-foreground">
                            <li><span className="text-zinc-200">Payments:</span> Processed via Dodo Payments. All major credit cards are accepted.</li>
                            <li><span className="text-zinc-200">Cancellations:</span> You may cancel your subscription at any time via the settings panel.</li>
                            <li><span className="text-zinc-200">Refunds:</span> Due to the high cost of real-time server-side scanning, refunds are generally not provided after credits have been consumed.</li>
                        </ul>
                    </Section>

                    <Section
                        icon={<Shield className="w-5 h-5 text-stone-300" />}
                        title="4. Limitation of Liability"
                    >
                        <p className="text-zinc-400 leading-relaxed">
                            TO THE MAXIMUM EXTENT PERMITTED BY LAW, MARDIS (MARDISHUB) AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES RESULTING FROM YOUR USE OF THE PLATFORM OR ANY CONTENT GENERATED THEREIN.
                        </p>
                    </Section>
                </div>

                <div className="mt-20 pt-10 border-t border-white/5 text-center">
                    <p className="text-sm text-muted-foreground">
                        Last updated: March 28, 2026. Your continued use constitutes acceptance of these evolving standards. Questions? Email <span className="text-white">hello@mardishub.com</span>
                    </p>
                </div>
            </div>
        </div>
    );
}

function Section({ icon, title, children }: { icon: React.ReactNode, title: string, children: React.ReactNode }) {
    return (
        <div className="p-8 bg-white/[0.02] border border-white/10 rounded-3xl backdrop-blur-xl">
            <div className="flex items-center gap-3 mb-6">
                <div className="p-2 bg-white/5 rounded-xl border border-white/10">
                    {icon}
                </div>
                <h2 className="text-2xl font-bold">{title}</h2>
            </div>
            <div className="text-muted-foreground leading-relaxed">
                {children}
            </div>
        </div>
    );
}
