"use client";

import { FileText, Scale, Zap, Globe, ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-[#0A0A0A] text-white font-sans selection:bg-primary/30">
            {/* Background elements */}
            <div className="fixed inset-0 overflow-hidden pointer-events-none">
                <div className="absolute top-[-10%] right-[-10%] w-[40%] h-[40%] bg-primary/10 blur-[120px] rounded-full" />
                <div className="absolute bottom-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/10 blur-[120px] rounded-full" />
            </div>

            <div className="relative max-w-4xl mx-auto px-6 py-20">
                <Link
                    href="/"
                    className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors mb-12 group"
                >
                    <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                    Back to Home
                </Link>

                <div className="grid gap-8 mt-16">
                    <Section
                        icon={<Zap className="w-5 h-5 text-primary" />}
                        title="Acceptable Use"
                    >
                        <p>Mardis provides tools for lead discovery and personalized outreach. You agree not to:</p>
                        <ul className="list-disc list-inside space-y-2 mt-4 text-muted-foreground">
                            <li>Use the platform for spamming or harassment of any individuals.</li>
                            <li>Attempt to scrape data in bulk for redistribution.</li>
                            <li>Misrepresent your identity or bypass platform rules.</li>
                        </ul>
                    </Section>

                    <Section
                        icon={<Globe className="w-5 h-5 text-primary" />}
                        title="AI Content Disclaimer"
                    >
                        <p>Our personalized DMs are generated by AI (Grok). While we aim for high quality:</p>
                        <ul className="list-disc list-inside space-y-2 mt-4 text-muted-foreground">
                            <li>You are solely responsible for reviewing and sending any AI-generated content.</li>
                            <li>We do not guarantee the accuracy or appropriateness of AI suggestions.</li>
                            <li>The AI's performance depends on the context and handles you provide.</li>
                        </ul>
                    </Section>

                    <Section
                        icon={<FileText className="w-5 h-5 text-primary" />}
                        title="Payment & Subscriptions"
                    >
                        <p>Access to premium features is provided on a subscription basis:</p>
                        <ul className="list-disc list-inside space-y-2 mt-4 text-muted-foreground">
                            <li>Subscriptions are non-refundable once the discovery credits have been used.</li>
                            <li>We reserve the right to modify pricing with 30-day notice to active users.</li>
                        </ul>
                    </Section>
                </div>

                <div className="mt-20 pt-10 border-t border-white/5 text-center">
                    <p className="text-sm text-muted-foreground">
                        Last updated: February 21, 2026. Your continued use of Mardis constitutes acceptance of these terms.
                    </p>
                </div>
            </div>
        </div>
    );
}

function Section({ icon, title, children }: { icon: React.ReactNode, title: string, children: React.ReactNode }) {
    return (
        <div className="p-8 bg-white/[0.02] border border-white/10 rounded-3xl backdrop-blur-xl">
            <div className="flex items-center gap-3 mb-6">
                <div className="p-2 bg-white/5 rounded-xl border border-white/10">
                    {icon}
                </div>
                <h2 className="text-2xl font-bold">{title}</h2>
            </div>
            <div className="text-muted-foreground leading-relaxed">
                {children}
            </div>
        </div>
    );
}
